# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.3
        env:
          webhook_url: "https://admiring-poitras.213-167-227-205.plesk.page:8443/modules/git/public/web-hook.php?uuid=6d6f4ac0-b91a-bce1-df6e-d786dedc82c1"
          webhook_secret: "2Nq@#WUu@Rn9GejB3wx47#Z2"
